// <auto-generated />
using System;
using System.Collections.Generic;
using HookRelay.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HookRelay.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HookRelayDbContext))]
    [Migration("20260828150906_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HookRelay.Domain.Deliveries.DeadLetter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("DeadLetteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at_utc");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("ReplayCount")
                        .HasColumnType("integer")
                        .HasColumnName("replay_count");

                    b.Property<DateTimeOffset?>("ReplayedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("replayed_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_dead_letters");

                    b.HasIndex("DeliveryId")
                        .IsUnique()
                        .HasDatabaseName("ix_dead_letters_delivery_id");

                    b.HasIndex("EndpointId", "DeadLetteredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_dead_letters_endpoint");

                    b.ToTable("dead_letters", (string)null);
                });

            modelBuilder.Entity("HookRelay.Domain.Deliveries.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at_utc");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<string>("OrderingKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ordering_key");

                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("ReplayCount")
                        .HasColumnType("integer")
                        .HasColumnName("replay_count");

                    b.Property<int>("SecretVersion")
                        .HasColumnType("integer")
                        .HasColumnName("secret_version");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_deliveries");

                    b.HasIndex("ClaimedAtUtc")
                        .HasDatabaseName("ix_deliveries_stale_claims")
                        .HasFilter("status = 1");

                    b.HasIndex("EndpointId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_deliveries_endpoint_log");

                    b.HasIndex("OrderingKey", "Id")
                        .HasDatabaseName("ix_deliveries_ordering_key")
                        .HasFilter("status IN (0, 1)");

                    b.HasIndex("Status", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_deliveries_due")
                        .HasFilter("status = 0");

                    b.ToTable("deliveries", (string)null);
                });

            modelBuilder.Entity("HookRelay.Domain.Deliveries.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset>("AttemptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at_utc");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("Error")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("error");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<string>("ResponseSnippet")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("response_snippet");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Id")
                        .HasName("pk_delivery_attempts");

                    b.HasIndex("DeliveryId", "AttemptNumber")
                        .HasDatabaseName("ix_delivery_attempts_history");

                    b.HasIndex("EndpointId", "AttemptedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_delivery_attempts_endpoint");

                    b.ToTable("delivery_attempts", (string)null);
                });

            modelBuilder.Entity("HookRelay.Domain.Endpoints.WebhookEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<int>("OrderingStrategy")
                        .HasColumnType("integer")
                        .HasColumnName("ordering_strategy");

                    b.Property<string>("ProtectedPreviousSecret")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("protected_previous_secret");

                    b.Property<string>("ProtectedSecret")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("protected_secret");

                    b.Property<DateTimeOffset?>("SecretRotatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("secret_rotated_at_utc");

                    b.Property<int>("SecretVersion")
                        .HasColumnType("integer")
                        .HasColumnName("secret_version");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.PrimitiveCollection<List<string>>("_subscribedEventTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("subscribed_event_types");

                    b.HasKey("Id")
                        .HasName("pk_webhook_endpoints");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_webhook_endpoints_tenant_id_status");

                    b.ToTable("webhook_endpoints", (string)null);
                });

            modelBuilder.Entity("HookRelay.Domain.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("aggregate_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.Property<int>("FanOutCount")
                        .HasColumnType("integer")
                        .HasColumnName("fan_out_count");

                    b.Property<string>("OrderingKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ordering_key");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("Status", "OrderingKey", "Id")
                        .HasDatabaseName("ix_outbox_messages_claim");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("HookRelay.Domain.Deliveries.DeliveryAttempt", b =>
                {
                    b.HasOne("HookRelay.Domain.Deliveries.Delivery", null)
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_attempts_deliveries_delivery_id");
                });
#pragma warning restore 612, 618
        }
    }
}
