using Npgsql;
using Testcontainers.Kafka;
using Testcontainers.PostgreSql;

namespace HookRelay.IntegrationTests;

/// <summary>
/// Real Postgres and real Kafka, shared by every test in the suite.
/// </summary>
/// <remarks>
/// An in-memory queue and an in-memory database would make these tests fast and worthless. The behaviour
/// under test is exactly the behaviour a stand-in gets wrong: <c>FOR UPDATE SKIP LOCKED</c>, partition
/// assignment, transaction visibility. Containers start once for the whole suite and each test class gets
/// its own database, which keeps isolation without paying for a container per class.
/// </remarks>
public sealed class ContainerFixture : IAsyncLifetime
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder("postgres:18-alpine")
        .WithDatabase("hookrelay")
        .WithUsername("hookrelay")
        .WithPassword("hookrelay")
        .Build();

    private readonly KafkaContainer _kafka = new KafkaBuilder("confluentinc/cp-kafka:7.8.0")
        .Build();

    /// <summary>Bootstrap servers for the shared broker.</summary>
    public string KafkaBootstrapServers => _kafka.GetBootstrapAddress();

    /// <inheritdoc />
    public async ValueTask InitializeAsync() =>
        await Task.WhenAll(_postgres.StartAsync(), _kafka.StartAsync());

    /// <inheritdoc />
    public async ValueTask DisposeAsync()
    {
        await _postgres.DisposeAsync();
        await _kafka.DisposeAsync();
    }

    /// <summary>Creates an empty database and returns a connection string for it.</summary>
    /// <param name="name">Database name. Must be unique within the run.</param>
    public async Task<string> CreateDatabaseAsync(string name)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);

        await using var connection = new NpgsqlConnection(_postgres.GetConnectionString());
        await connection.OpenAsync();

        await using (NpgsqlCommand command = connection.CreateCommand())
        {
            // Identifiers cannot be parameterised. The name is generated by the suite, never user input,
            // and is restricted to characters that cannot terminate the quoted identifier.
            command.CommandText = $"""CREATE DATABASE "{Sanitize(name)}" """;
            await command.ExecuteNonQueryAsync();
        }

        var connectionString = new NpgsqlConnectionStringBuilder(_postgres.GetConnectionString())
        {
            Database = Sanitize(name),
        };

        return connectionString.ToString();
    }

    private static string Sanitize(string name) =>
        new([.. name.Where(static character => char.IsAsciiLetterOrDigit(character) || character == '_')]);
}

/// <summary>Binds the container fixture to every collection that needs infrastructure.</summary>
[CollectionDefinition(Name)]
public sealed class InfrastructureFixtureBinding : ICollectionFixture<ContainerFixture>
{
    /// <summary>Collection name.</summary>
    public const string Name = "infrastructure";
}
